[package]
name = "overlook"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
humantime = "2.1.0"
palette = "0.7.6"
rand = "0.8.5"
